[package]
name = "tetrus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.28"
macroquad = "0.3.25"
ordered-float = "3.7.0"
rand = "0.8"
rustop = "1.1.2"
